"""User-facing CLI for confer per CLI Inject Tool (ci7n4pvm).

Subcommands:
  confer list           — show pending asks the user can answer
  confer answer "text"  — apply Reply Routing Rules to text and report outcome
  confer setup          — scaffold config + register with Claude (st7nqkp4)

The list/answer commands connect to the daemon's Unix socket but do NOT send
HELLO; the CLI is a user-side injector, not an MCP-spawned client. Inject and
ListAsks are HELLO-exempt on the daemon side per the STATUS precedent
(xn7pqv4m). The setup command touches no daemon — it is the post-install
ceremony for confer setup Subcommand (st7nqkp4).
"""

import argparse
import asyncio
import json
import os
import shutil
import subprocess
import sys
import uuid

from confer import hooks, integrations, presence
from confer.config import default_config_path
from confer.paths import socket_path
from confer.protocol import (
    Inject,
    InjectResult,
    ListAsks,
    ListAsksResult,
    Message,
    decode,
    encode,
)


# Outcomes where nothing reached an agent → non-zero exit so a script
# branching on `confer answer` status behaves correctly (ci7n4pvm).
# delivered / queued_notify_reply / broadcast are successes (exit 0).
_NON_ZERO_EXIT_OUTCOMES = {"bounced", "ambiguous", "concierge"}


async def _send_one(msg: Message) -> Message:
    """Open a one-shot connection, send msg, read one response line, close."""
    sock = socket_path()
    try:
        reader, writer = await asyncio.open_unix_connection(str(sock))
    except (FileNotFoundError, ConnectionRefusedError) as exc:
        print(
            f"confer: cannot reach daemon at {sock} ({exc.__class__.__name__}). "
            f"Is the daemon running? Try opening any MCP client to auto-spawn it.",
            file=sys.stderr,
        )
        sys.exit(2)
    try:
        try:
            writer.write(encode(msg))
            await writer.drain()
            line = await reader.readline()
        except (ConnectionResetError, BrokenPipeError):
            line = b""
    finally:
        writer.close()
        try:
            await writer.wait_closed()
        except Exception:
            pass
    if not line:
        print("confer: daemon closed connection before responding.", file=sys.stderr)
        sys.exit(2)
    return decode(line)


async def _cmd_list() -> int:
    response = await _send_one(ListAsks(request_id=str(uuid.uuid4())))
    if not isinstance(response, ListAsksResult):
        print(
            f"confer: unexpected response from daemon: {type(response).__name__}",
            file=sys.stderr,
        )
        return 2
    print(response.formatted)
    return 0


async def _cmd_answer(text: str) -> int:
    response = await _send_one(
        Inject(request_id=str(uuid.uuid4()), content=text)
    )
    if not isinstance(response, InjectResult):
        print(
            f"confer: unexpected response from daemon: {type(response).__name__}",
            file=sys.stderr,
        )
        return 2
    print(response.detail)
    return 1 if response.outcome in _NON_ZERO_EXIT_OUTCOMES else 0


def _toml_escape(s: str) -> str:
    """Escape a value for a TOML basic string. Discord tokens are
    [A-Za-z0-9._-] so this is belt-and-suspenders, but it keeps a pasted
    value with a stray quote/backslash from producing invalid config."""
    return s.replace("\\", "\\\\").replace('"', '\\"')


def _render_config(token: str, user_id: int) -> str:
    return (
        "# confer daemon configuration (generated by `confer setup`).\n"
        "# Permissions: 0600. Regenerate with `confer setup --force`.\n\n"
        f'discord_bot_token = "{_toml_escape(token)}"\n'
        f"confer_user_id = {user_id}\n"
    )


def _register_with_claude() -> None:
    """Best-effort `claude mcp add` so the MCP client knows about confer.
    Prints the manual command on any path that doesn't end in success, so
    the user is never left guessing (st7nqkp4)."""
    manual = "  claude mcp add confer -- confer-server"
    claude = shutil.which("claude")
    if claude is None:
        print(
            "'claude' CLI not found on PATH; skipping auto-registration.\n"
            "To register manually:\n" + manual
        )
        return
    result = subprocess.run(["claude", "mcp", "add", "confer", "--", "confer-server"])
    if result.returncode == 0:
        print("Registered confer with Claude Code (claude mcp add).")
    else:
        print(
            f"'claude mcp add' exited {result.returncode}; register manually:\n"
            + manual,
            file=sys.stderr,
        )


def _cmd_setup(
    *,
    token: str | None,
    user_id: str | None,
    force: bool,
    register: bool,
    with_integrations: bool = False,
    input_fn=input,
) -> int:
    """Post-install ceremony: write ~/.config/confer/config.toml (0600) and,
    unless --no-register, run `claude mcp add` (st7nqkp4)."""
    path = default_config_path()
    if path.exists() and not force:
        print(
            f"confer: config already exists at {path}; refusing to overwrite. "
            "Re-run with --force to replace it (discards the existing token).",
            file=sys.stderr,
        )
        return 1

    if token is None:
        token = input_fn("Discord bot token: ").strip()
    if not token:
        print("confer: a non-empty Discord bot token is required.", file=sys.stderr)
        return 1

    if user_id is None:
        user_id = input_fn("Your Discord user id (snowflake, digits): ").strip()
    if not user_id.isdigit() or int(user_id) <= 0:
        print(
            f"confer: confer_user_id must be a positive integer snowflake "
            f"(got {user_id!r}).",
            file=sys.stderr,
        )
        return 1

    path.parent.mkdir(parents=True, exist_ok=True)
    os.chmod(path.parent, 0o700)
    path.write_text(_render_config(token, int(user_id)))
    os.chmod(path, 0o600)
    print(f"Wrote {path} (mode 0600).")

    if register:
        _register_with_claude()
    else:
        print(
            "Skipped Claude registration. To register manually:\n"
            "  claude mcp add confer -- confer-server"
        )
    if with_integrations:
        print("Installing away-mode integrations:")
        for action in integrations.install(dry_run=False):
            print(f"  - {action}")
    print(
        "Setup complete. Open an MCP client and confer will auto-spawn its daemon."
    )
    return 0


def _cmd_away(note: str | None) -> int:
    presence.set_away(note)
    msg = "confer: away mode ON — agents will reach you via Discord."
    if note:
        msg += f' (note: "{note}")'
    print(msg)
    return 0


def _cmd_back() -> int:
    presence.set_present()
    print("confer: away mode OFF — back at the keyboard.")
    return 0


def _cmd_presence() -> int:
    p = presence.read_presence()
    if not p.away:
        print("present")
        return 0
    suffix = f' — note: "{p.note}"' if p.note else ""
    print(f"away{suffix}")
    return 0


def _cmd_hook(event: str) -> int:
    """Internal: dispatch a Claude Code hook event (eh7nqkp4 / ar7nqkp4)."""
    if event == "prompt":
        return hooks.run_prompt_hook()
    code, stderr_text = hooks.run_stop_hook(sys.stdin.read())
    if stderr_text:
        print(stderr_text, file=sys.stderr)
    return code


def _cmd_install_hooks(*, dry_run: bool) -> int:
    try:
        actions = integrations.install(dry_run=dry_run)
    except json.JSONDecodeError as exc:
        print(
            f"confer: {integrations.claude_dir() / 'settings.json'} is not "
            f"valid JSON ({exc}); refusing to modify it. Fix it and re-run.",
            file=sys.stderr,
        )
        return 1
    print("Would apply:" if dry_run else "Applied:")
    for action in actions:
        print(f"  - {action}")
    return 0


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="confer",
        description=(
            "User-side CLI for the confer daemon. Lets you answer pending "
            "agent asks from the laptop without going through Discord."
        ),
    )
    sub = parser.add_subparsers(dest="cmd", required=True)
    sub.add_parser("list", help="List pending asks newest-first.")
    answer = sub.add_parser(
        "answer",
        help=(
            "Send text to the daemon, routed by the same rules as a Discord "
            "DM. Address a specific thread with 're <tag> ...' (a unique tag "
            "prefix is fine, e.g. 're k3 ...'), or just send text when only "
            "one ask is pending. With no pending ask, the text is broadcast "
            "to all connected agents. See 'confer list' for open asks and "
            "their tags."
        ),
    )
    answer.add_argument("text", help="Reply or message body.")
    setup = sub.add_parser(
        "setup",
        help=(
            "Scaffold ~/.config/confer/config.toml (mode 0600) and register "
            "the MCP server with Claude Code. Run once after installing."
        ),
    )
    setup.add_argument(
        "--token", help="Discord bot token (prompted interactively if omitted)."
    )
    setup.add_argument(
        "--user-id",
        dest="user_id",
        help="Your Discord user id snowflake (prompted if omitted).",
    )
    setup.add_argument(
        "--force",
        action="store_true",
        help="Overwrite an existing config.toml.",
    )
    setup.add_argument(
        "--no-register",
        dest="register",
        action="store_false",
        help="Skip the 'claude mcp add' registration step.",
    )
    setup.add_argument(
        "--integrations",
        action="store_true",
        help="Also install the away-mode Stop/UserPromptSubmit hooks and "
        "/away /back slash commands (same as 'confer install-hooks').",
    )

    away = sub.add_parser(
        "away",
        help=(
            "Turn on away mode: every confer-aware session reaches you via "
            "Discord instead of waiting at the terminal. Run from any window."
        ),
    )
    away.add_argument(
        "--note",
        default=None,
        help="Optional note surfaced to agents (e.g. 'back after lunch').",
    )
    sub.add_parser(
        "back",
        help="Turn off away mode (also happens automatically when you type).",
    )
    sub.add_parser("presence", help="Print current presence (away/present).")

    hook = sub.add_parser(
        "hook",
        help="Internal: Claude Code hook entry points (used by install-hooks).",
    )
    hook.add_argument("event", choices=["stop", "prompt"])

    install = sub.add_parser(
        "install-hooks",
        help=(
            "Install the away-mode hooks and /away /back slash commands into "
            "~/.claude. Idempotent; merges into existing settings."
        ),
    )
    install.add_argument(
        "--print",
        dest="dry_run",
        action="store_true",
        help="Show what would change without writing anything.",
    )
    return parser


def main(argv: list[str] | None = None) -> int:
    args = _build_parser().parse_args(argv)
    if args.cmd == "list":
        return asyncio.run(_cmd_list())
    if args.cmd == "answer":
        return asyncio.run(_cmd_answer(args.text))
    if args.cmd == "away":
        return _cmd_away(args.note)
    if args.cmd == "back":
        return _cmd_back()
    if args.cmd == "presence":
        return _cmd_presence()
    if args.cmd == "hook":
        return _cmd_hook(args.event)
    if args.cmd == "install-hooks":
        return _cmd_install_hooks(dry_run=args.dry_run)
    return _cmd_setup(
        token=args.token,
        user_id=args.user_id,
        force=args.force,
        register=args.register,
        with_integrations=args.integrations,
    )


if __name__ == "__main__":  # pragma: no cover
    sys.exit(main())
